name: Autoupdate
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
    steps:
      - name: Autoupdate
        uses: siarheidudko/autoupdater@v1
        with:
          stages: 'sudo npm install firebase-tools nyc mocha -g&&echo $SERVICE_ACCOUNT > serviceAccount.json&&npm run lint&&npm run build&&npm run cov&&npm run doc'