name: Autoupdate
on:
  push
jobs:
  check-updates:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
    steps:
      - name: set service account file
        id: save_service_account
        run: echo $SERVICE_ACCOUNT>./serviceAccount.json
      - name: install test dependencies
        id: install_dependencies
        run: sudo npm install firebase-tools nyc mocha eslint typedoc typescript -g
      - name: Autoupdate
        id: autoupdate
        uses: siarheidudko/autoupdater@v1
        with:
          stages: 'npm run lint&&npm run build&&npm run cov&&npm run doc'
      - run: echo ${{ steps.autoupdate.outputs.updated }}