name: Autoupdate
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Autoupdate
        uses: siarheidudko/autoupdater@v1
        with:
          stages: 'npm ci&&sudo npm install firebase-tools nyc mocha -g&&npm run lint&&npm run build&&npm run cov&&npm run doc'