name: Deploy Cloud Functions to production
on:
  push:
    branches:
      - master
jobs:
  linting:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      NODE_VERSION: 10
    steps:
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install linter
        run: sudo npm install tslint -g
      - run: sudo ls -l
      - name: Run linter
        run: npm run lint
